# I removed the bloat in this file, look at https://jekyllrb.com/ if you're new to jekyll and need more info.

title: Codewell Newsie Newsletter
description: >-
  Codewell mockup translated from a .png design to HTML. This one is for their Newsie Newsletter
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
lang: en # the language your site is written in
themecolor: "" # the theme Color for Chrome, Firefox OS and Opera
plugins:
  - jekyll-feed

permalink: /:title:output_ext # post output path
